# Generated by Django 4.2.7 on 2024-03-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredentials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='firstName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
